// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pool/pool": {
            "post": {
                "description": "创建池",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph池模块"
                ],
                "summary": "创建池",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除池",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph池模块"
                ],
                "summary": "删除池",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/pool/pools": {
            "post": {
                "description": "获取到所有的pool",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph池模块"
                ],
                "summary": "获取到所有的pool",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/rbd/image": {
            "post": {
                "description": "创建image",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph rbd模块"
                ],
                "summary": "创建image",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除image",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph rbd模块"
                ],
                "summary": "删除image",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/rbd/images": {
            "post": {
                "description": "获取到所有的image",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph rbd模块"
                ],
                "summary": "获取到所有的image",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/snap/clone": {
            "post": {
                "description": "快照克隆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph snaphost模块"
                ],
                "summary": "快照克隆",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "oldImageName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新的image名称",
                        "name": "newImageName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "快照名称",
                        "name": "snapName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/snap/protect": {
            "post": {
                "description": "锁定快照",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph snaphost模块"
                ],
                "summary": "锁定快照",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "快照名称",
                        "name": "snapName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/snap/rollback": {
            "post": {
                "description": "快照回滚",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph snaphost模块"
                ],
                "summary": "快照回滚",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "快照名称",
                        "name": "snapName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/snap/snaphost": {
            "post": {
                "description": "获取快照信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph snaphost模块"
                ],
                "summary": "获取快照信息",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "快照名称",
                        "name": "snapName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除快照",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph snaphost模块"
                ],
                "summary": "删除快照",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "快照名称",
                        "name": "snapName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/snap/snaphost/create": {
            "post": {
                "description": "创建快照",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph snaphost模块"
                ],
                "summary": "创建快照",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "快照名称",
                        "name": "snapName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/snap/snaphosts": {
            "post": {
                "description": "获取到所有的快照",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph snaphost模块"
                ],
                "summary": "获取到所有的快照",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        },
        "/snap/unprotect": {
            "post": {
                "description": "解锁快照",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ceph snaphost模块"
                ],
                "summary": "解锁快照",
                "parameters": [
                    {
                        "description": "连接配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ConnConfig"
                        }
                    },
                    {
                        "type": "string",
                        "description": "池名称",
                        "name": "poolName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image名称",
                        "name": "imageName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "快照名称",
                        "name": "snapName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ResponseBean"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.ConnConfig": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "Ceph Mgr ipaddr",
                    "example": "192.168.113.215:6789,192.168.113.216:6789,192.168.113.217:6789"
                },
                "key": {
                    "type": "string",
                    "format": "Mgr 密钥Key",
                    "example": "AQB+AsFew2rtHRAAwEpQAa1LOG9cYK7k66vtQA=="
                },
                "user": {
                    "type": "string",
                    "format": "用户名",
                    "example": "admin"
                }
            }
        },
        "web.ResponseBean": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "Ceph Rest Api",
	Description: "基于go-ceph封装的Rest Api",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
