basePath: /api
definitions:
  web.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 基于go-ceph封装的Rest Api
  license: {}
  title: Ceph Rest Api
  version: "1.0"
paths:
  /pool/pools:
    get:
      consumes:
      - application/json
      description: 获取到所有的pool
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: We need ID!!
          schema:
            $ref: '#/definitions/web.APIError'
        "404":
          description: Can not find ID
          schema:
            $ref: '#/definitions/web.APIError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/web.APIError'
      summary: 获取到所有的pool
      tags:
      - ceph池模块
swagger: "2.0"
