basePath: /api
definitions:
  web.ResponseBean:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 基于go-ceph封装的Rest Api
  license: {}
  title: Ceph Rest Api
  version: "1.0"
paths:
  /pool/{poolName}:
    get:
      consumes:
      - application/json
      description: 获取到所有的pool
      parameters:
      - description: 池名称
        in: path
        name: poolName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.ResponseBean'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ResponseBean'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ResponseBean'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ResponseBean'
      summary: 通过名称获取对应池信息
      tags:
      - ceph池模块
  /pool/pools:
    get:
      consumes:
      - application/json
      description: 获取到所有的pool
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.ResponseBean'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ResponseBean'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ResponseBean'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ResponseBean'
      summary: 获取到所有的pool
      tags:
      - ceph池模块
swagger: "2.0"
